# Dependencies
markdown: kramdown

kramdown:
  input: GFM

pygments: false

# Permalinks
permalink: '/announcements/:title'

# Setup
title: Caliburn.Micro
tagline: 'Xaml made easy'
description: 'An opinionated MVVM framework for all Xaml platforms.'
url: http://caliburnmicro.com

author:
  name: 'Nigel Sampson'
  url: https://twitter.com/nigelsampson

paginate: 5
paginate_path: '/announcements/:num'

# Custom vars
version: 2.0.0

github:
  repo: https://github.com/caliburn-micro/caliburn.micro
